apiVersion: v1
kind: Service
metadata:
  name: ollama-webui
  namespace: ollama
spec:
  selector:
    app: ollama-webui
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: LoadBalancer
